apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeprediction-api
spec:
  selector:
    matchLabels:
      run: makeprediction-api
  replicas: 1
  template:
    metadata:
      labels:
        run: makeprediction-api
    spec:
      containers:
      - name: makeprediction-api
        image: mcastellin/udacity-make-prediction:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: makeprediction-api
  labels:
    run: makeprediction-api
spec:
  ports:
  - port: 80
  selector:
    run: makeprediction-api
